#!/bin/bash
# Quick reference: How to read documentation files in bash

echo "============================================================"
echo "SIMPLES Compiler - Quick Start in Bash"
echo "============================================================"
echo ""
echo "📚 READING DOCUMENTATION"
echo "============================================================"
echo ""
echo "To read files in bash, use one of these commands:"
echo ""
echo "  cat GETTING_STARTED.md"
echo "  less GETTING_STARTED.md"
echo "  head -20 GETTING_STARTED.md"
echo ""
echo "Examples:"
echo "  cat START_HERE.txt                # Show entire file"
echo "  cat README.md                     # Show documentation"
echo "  head -50 GETTING_STARTED.md       # Show first 50 lines"
echo ""
echo "============================================================"
echo "🔨 BUILDING & TESTING"
echo "============================================================"
echo ""
echo "Since 'make' is not installed, use Python build script:"
echo ""
echo "  python build.py test              # Build and test lexer"
echo "  python build.py clean             # Clean build artifacts"
echo "  python build.py all               # Build everything"
echo ""
echo "============================================================"
echo "⚡ QUICK START"
echo "============================================================"
echo ""
echo "1. Organize project files:"
echo "   python FINAL_SETUP.py"
echo ""
echo "2. Read the guide:"
echo "   cat GETTING_STARTED.md"
echo ""
echo "3. Build and test:"
echo "   python build.py test"
echo ""
echo "4. See progress:"
echo "   cat STATUS.md"
echo ""
echo "5. Start coding:"
echo "   cat plan.md | head -200"
echo ""
echo "============================================================"
echo "📂 IMPORTANT FILES"
echo "============================================================"
echo ""
echo "START_HERE.txt         Quick orientation (short)"
echo "GETTING_STARTED.md     Setup guide (medium)"
echo "README.md              Main docs (medium)"
echo "DOCUMENTATION.md       Full spec (long)"
echo "plan.md                Task breakdown (very long, 40+ KB)"
echo "STATUS.md              Progress tracker (short)"
echo "SETUP_WINDOWS.md       Windows setup guide"
echo ""
echo "============================================================"
echo "📋 NEXT STEPS"
echo "============================================================"
echo ""
echo "1. cat START_HERE.txt"
echo "2. python FINAL_SETUP.py"
echo "3. python build.py test"
echo "4. cat GETTING_STARTED.md"
echo ""
echo "============================================================"
